#!/bin/sh

# PROVIDE: ai_log_collector
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="ai_log_collector"
rcvar="ai_log_collector_enable"
command="/usr/local/bin/ai_log_collector.php"
pidfile="/var/run/${name}.pid"

load_rc_config $name
run_rc_command "$1"
